#!bin/bash
# Platform: Ubuntu in WSL2, miniforge with python3.12, cuda 11.8
# cuda path is needed, python path is also needed
# verify cuda version
  # check conda environments and make sure conda is deactivated
conda info --envs
conda deactivate
nvcc --version
  # log
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

  # get your cuda path
ls /usr/local/cuda-11.8
  # check log that it is cuda executable path

# Install from source
  # Clone this repository and cd inside
git clone https://github.com/rsanchezgarc/deepEMhancer
cd deepEMhancer

  # Create a conda environment with the required dependencies
  # edit to comment out cudatoolkit 11.8 (we will use system wide installed cuda-12.8)
conda env create -f deepEMhancer_env.yml  -n deepEMhancer_env

  # Activate the environment. Also activate the environment before executing deepEMhancer
conda activate deepEMhancer_env

  # Tensorflow install to use with cuda 12.8 system wide
First, check if system cuda & version 12.8 is found
$which nvcc (should be system cuda home dir)
$nvcc --version (should get 12.8)
Then, check which tensorflow is in the the env (it is tensorflow v2.12. minimum 2.15 is needed to work with cuda-12.8)
$pip show tensorflow (alternative easy way for pip or do the following to find out)
$python
$import tensorflow as tf
$print(tf.__version__)
$exit()

Uninstall tensorflow 2.12
$pip uninstall tensorflow

  # Install tensorflow 2.15 
$pip install --upgrade pip
$pip install tensorflow==2.15.0

  # Verify that tensorflow is 2.15 (as above) and it gets GPU devices
$print("GPUs:", tf.config.list_physical_devices("GPU")) [should give device 0.. ]

  # Install deepEMhancer
python -m pip install . --no-deps
# log
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Processing /mnt/c/Linux_folder/deepEMhancer
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: deepEMhancer
  Building wheel for deepEMhancer (setup.py) ... done
  Created wheel for deepEMhancer: filename=deepemhancer-0.16-py3-none-any.whl size=35277 sha256=62958afe7233bdfea7edb0ca870c162b1a6e927656378ee45260bb997f8b9d7c
  Stored in directory: /tmp/pip-ephem-wheel-cache-gdh8u6d0/wheels/7d/ef/9c/aad6dfd2419dec8faad7ca3ad5bc99c4d09d97bec7e4ad4c7e
Successfully built deepEMhancer
Installing collected packages: deepEMhancer
Successfully installed deepEMhancer-0.16

  # Download our deep learning models
deepemhancer --download
# Do not forget to activate the environment for future usages
# Ref: https://github.com/rsanchezgarc/deepEMhancer

